// Auto-generated by Makefile
#pragma once
#define KERNEL_VERSION_MAJOR 1
#define KERNEL_VERSION_MINOR 0
#define KERNEL_VERSION_PATCH 0
#define KERNEL_VERSION_SUFFIX "-alpha"
#define KERNEL_VERSION_STRING \
    "1.0.0-alpha"
